# stats available at
# https://travis-ci.org/strukturag/spreed-speakfreely/
language: go

go:
  - 1.1
  - 1.2
  - tip

env:
  - GEM_HOME=/var/lib/gems/1.8

before_install:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get update

install:
  - sudo apt-get -y install nodejs rubygems python-babel
  - sudo gem install compass
  - sudo npm install -g po2json
  - sudo npm install -g autoprefixer

script:
  - make get
  - make styles
  - make javascript
  - make binary
